export interface Post { slug: string; title: string; excerpt: string; category: string; author: string; authorTitle: string; readTime: string; date: string; coverImage: string; content: string; }

export const posts: Post[] = [
  { slug: 'ecg-smartwatches-2025', title: 'ECG Smartwatches: What They Can and Cannot Detect in 2025',
    excerpt: 'From AFib to long QT syndrome — a cardiologist explains what consumer ECG can actually find.',
    category: 'Heart Health', author: 'Dr. Tobias Muller', authorTitle: 'Chief Medical Officer', readTime: '8 min', date: '2025-12-02', coverImage: '/generated/blog-cover-ecg.webp',
    content: `<p>Electrocardiogram (ECG) technology has moved from hospital rooms to your wrist. But what can a consumer smartwatch ECG actually detect — and what remains firmly in the domain of a 12-lead clinical ECG?</p><h2>What a smartwatch ECG CAN detect</h2><p><strong>Atrial Fibrillation (AFib)</strong>: This is the flagship use case. Lumivex Apex detects AFib with 98.2% sensitivity, FDA-cleared. AFib affects 33 million people globally and increases stroke risk 5x. The watch continuously monitors for irregular rhythm and alerts within 30 seconds of detection.</p><p><strong>Bradycardia and Tachycardia</strong>: Abnormally slow (< 50 BPM) or fast (> 120 BPM) heart rates at rest are reliably flagged. These can indicate underlying conditions from electrolyte imbalances to thyroid disorders.</p><p><strong>QT Interval Prolongation</strong>: Emerging research shows single-lead ECG can screen for drug-induced QT prolongation — a potentially fatal side effect of certain medications.</p><h2>What it CANNOT detect</h2><p><strong>Heart Attack (MI)</strong>: A smartwatch ECG is a single-lead rhythm strip. It cannot detect ST-elevation myocardial infarction (STEMI), which requires a 12-lead ECG. If you have chest pain, seek emergency care — do not rely on your watch.</p><p><strong>Structural Heart Disease</strong>: Valve problems, chamber enlargement, and cardiomyopathies require echocardiography. The watch ECG sees electrical activity, not anatomy.</p><p><strong>Silent Ischemia</strong>: Reduced blood flow to heart muscle without symptoms cannot be detected by a single-lead wearable.</p><h2>The Bottom Line</h2><p>A smartwatch ECG is a screening tool, not a diagnostic device. It excels at detecting rhythm abnormalities — especially AFib — but should never replace professional medical evaluation. Think of it as an early warning system, not a doctor on your wrist.</p>` },
  { slug: 'sleep-score-dropped', title: 'Why Your Sleep Score Dropped and What to Do About It',
    excerpt: 'Five most common drivers of poor sleep scores and exactly how to fix each one.',
    category: 'Sleep', author: 'Dr. Anika Sharma', authorTitle: 'Co-CEO & Chief Science Officer', readTime: '6 min', date: '2025-11-28', coverImage: '/generated/blog-cover-sleep.webp',
    content: `<p>You wake up, check your Lumivex, and your sleep score dropped from 85 to 62. Panic sets in. But before you overhaul your entire nighttime routine, understand what drives sleep scores — and which factors you can actually control.</p><h2>The 5 drivers of sleep score</h2><p><strong>1. Sleep Duration (25%)</strong>: The most obvious. 7-9 hours is optimal for adults. Less than 6 hours tanks your score. But more than 10 hours can also indicate poor sleep quality.</p><p><strong>2. Sleep Stages (20%)</strong>: Deep sleep and REM are where recovery happens. Alcohol before bed fragments REM. Caffeine after 2 PM reduces deep sleep by up to 20%.</p><p><strong>3. Resting Heart Rate Drop (15%)</strong>: Your heart rate should dip 10-20% during sleep. No dip suggests your body is still in "alert" mode — common with late exercise, stress, or heavy meals before bed.</p><p><strong>4. SpO2 Stability (20%)</strong>: Oxygen levels should stay above 95% all night. Dips below 90% for more than 5 minutes trigger the sleep apnea risk alert. This is one you should take seriously — untreated sleep apnea doubles cardiovascular risk.</p><p><strong>5. Movement (20%)</strong>: Some movement is normal. But frequent tossing suggests discomfort, temperature issues, or a partner's snoring.</p><h2>Quick fixes</h2><p>Consistent bedtime/wake time (even weekends). No screens 30 minutes before bed. Room temperature 65-68 degrees Fahrenheit. No alcohol within 3 hours of sleep. These four changes alone improve the average sleep score by 12 points in our user data.</p>` },
  { slug: 'hrv-explained', title: 'Heart Rate Variability: What Your Watch Is Trying to Tell You',
    excerpt: 'HRV is the most misunderstood health metric. What a high or low score actually means.',
    category: 'Fitness', author: 'Dr. Marcus Chen', authorTitle: 'Head of AI & Data Science', readTime: '7 min', date: '2025-12-01', coverImage: '/generated/blog-cover-fitness.webp',
    content: `<p>Heart Rate Variability (HRV) is not your heart rate. It is the variation in time between each heartbeat — measured in milliseconds. A healthy heart does not beat like a metronome; it adapts constantly to your breathing, stress, and environment.</p><h2>High HRV = Good (usually)</h2><p>A high HRV means your autonomic nervous system is flexible. Your body can quickly switch between "fight or flight" (sympathetic) and "rest and digest" (parasympathetic) modes. Athletes typically have high HRV. It is a sign of good recovery and cardiovascular fitness.</p><h2>Low HRV = Pay attention</h2><p>A sudden drop in HRV is one of the most reliable early indicators of: overtraining, illness onset (sometimes 24-48 hours before symptoms), poor sleep recovery, or elevated stress. HealthCore AI tracks your personal HRV baseline over 72 hours and alerts when you deviate significantly.</p><h2>How to improve HRV</h2><p>Consistent sleep schedule. Regular aerobic exercise (but not overtraining). Meditation and breathwork (5 minutes of 4-7-8 breathing can boost HRV within 10 minutes). Limit alcohol — even one drink can suppress HRV for 24+ hours. Cold exposure (30-second cold shower) stimulates vagal tone.</p><h2>What is a "good" HRV?</h2><p>There is no universal number. HRV is highly individual — a 40ms reading might be excellent for one person and poor for another. Trend matters more than absolute value. Track your personal range over weeks, not days.</p>` },
  { slug: 'smartwatch-buying-guide', title: 'Smartwatch Buying Guide 2025: The Only Comparison That Matters',
    excerpt: '14 smartwatches tested for health accuracy. Only four passed clinical benchmarks.',
    category: 'Buying Guides', author: 'James Whitfield', authorTitle: 'Co-CEO & Chief Design Officer', readTime: '12 min', date: '2025-11-20', coverImage: '/generated/brand-hero-wide.webp',
    content: `<p>We bought 14 smartwatches ranging from $149 to $799. We tested each against clinical-grade reference devices in a controlled lab environment. The results were surprising — and should change how you shop.</p><h2>How we tested</h2><p>Heart rate accuracy: compared against a Polar H10 chest strap (gold standard) during rest, walking, running, and cycling. SpO2: compared against a Masimo clinical pulse oximeter. Sleep staging: compared against polysomnography (PSG) in a sleep lab. Blood pressure: compared against an arterial line in a clinical setting (487 participants).</p><h2>The 4 watches that passed</h2><p>Lumivex Apex (98.2% AFib sensitivity, ±2 BPM heart rate, ±1% SpO2). Apple Watch Ultra 2 (excellent heart rate, strong ecosystem, 36-hour battery limitation). Garmin Fenix 8 (best GPS, 16-day battery, no blood pressure). Oura Ring 4 (best sleep staging, no display, subscription required).</p><h2>What surprised us</h2><p>Price does not predict accuracy. Two $400+ watches failed our heart rate test during interval training. Budget watches under $100 performed essentially at random for SpO2. The best value in our test was mid-range ($179-299) — the Lumivex Pulse and similarly priced competitors delivered 90%+ of flagship accuracy at half the cost.</p><h2>Our recommendation</h2><p>If health accuracy is your priority, buy a device with FDA-cleared ECG. If you are a serious athlete, dual-band GPS and running dynamics matter more than ECG. If you just want better sleep, a ring form factor may be more comfortable than a watch for overnight wear. There is no single "best" — only the best for your specific needs.</p>` },
  { slug: 'bp-accuracy-comparison', title: 'Blood Pressure Accuracy: Smartwatch vs. Cuff vs. Arterial Line',
    excerpt: 'Three measurement methods compared head-to-head in a 500-person study.',
    category: 'Research', author: 'Dr. Marcus Chen', authorTitle: 'Head of AI & Data Science', readTime: '10 min', date: '2025-12-05', coverImage: '/generated/blog-cover-bp.webp',
    content: `<p>Blood pressure is the single most important vital sign for cardiovascular health. Hypertension affects 1.3 billion people globally and causes 7.5 million deaths annually. Accurate measurement matters.</p><h2>The gold standard: Arterial line</h2><p>An intra-arterial catheter provides continuous, beat-to-beat blood pressure. It is invasive, requires a hospital setting, and is used as the reference in clinical validation studies. Our validation study used arterial line measurements as ground truth.</p><h2>The home standard: Arm cuff</h2><p>Oscillometric arm cuffs are the standard for home monitoring. Accuracy is ±3 mmHg compared to arterial lines when used correctly. However, 60% of home users position the cuff incorrectly, use the wrong size, or measure at inconsistent times — reducing real-world accuracy significantly.</p><h2>The new option: Smartwatch</h2><p>Lumivex uses Pulse Transit Time (PTT) — the time delay between the ECG R-wave and the PPG pulse arrival at the wrist. Faster PTT = higher blood pressure. Our clinical validation showed mean absolute difference of 5.2 mmHg systolic and 3.9 mmHg diastolic vs arterial line. This is within the ISO 81060-2 standard for clinical grade.</p><h2>Key caveat</h2><p>PTT-based blood pressure requires monthly calibration with a standard arm cuff. Without calibration, accuracy drifts over time. It is best used for trend monitoring and early warning, not for medication dosing decisions.</p>` },
  { slug: 'best-swim-smartwatch', title: 'Best Smartwatch for Swimming: Pool, Open Water, Triathlon',
    excerpt: 'Six watches tested in pool and open water. GPS accuracy and heart rate compared.',
    category: 'Fitness', author: 'Sofia Reyes', authorTitle: 'VP of Engineering', readTime: '9 min', date: '2025-11-25', coverImage: '/generated/scene-gym.webp',
    content: `<p>Swimming is the ultimate test for a smartwatch. Water blocks radio signals, movement is complex, and heart rate measurement through water is notoriously difficult.</p><h2>The tests</h2><p>Pool: 100m freestyle intervals, stroke detection accuracy, lap counting. Open water: 1km ocean swim, GPS track accuracy vs a Garmin handheld. Heart rate: chest strap vs watch during 400m IM (all four strokes).</p><h2>Results</h2><p>Lumivex Apex and Apex Sport (5ATM, 50m rated) correctly identified all four swim strokes with 94% accuracy. Lap counting was perfect in pool mode. Open water GPS tracked within 5 meters of the reference device. Heart rate during swimming was within ±3 BPM of chest strap — impressive given water's signal attenuation.</p><p>Key limitation: touchscreen is disabled underwater. All interactions use the physical side button and crown. This is deliberate — water registers as false touch input — but takes getting used to.</p><h2>Bottom line</h2><p>For pool swimmers, Pulse and above all perform well. For open water and triathlon, Apex Sport adds satellite SOS and better GPS. Do not swim with Core (IP68, not 5ATM). Pulse Kids is pool-safe (IP68).</p>` },
  { slug: 'sleep-apnea-home', title: 'Sleep Apnea Detection at Home: What Your Watch Can and Cannot Do',
    excerpt: 'Consumer SpO2 monitoring is improving fast but is not a substitute for a sleep study.',
    category: 'Sleep', author: 'Dr. Anika Sharma', authorTitle: 'Co-CEO', readTime: '8 min', date: '2025-11-12', coverImage: '/generated/scene-family.webp',
    content: `<p>Sleep apnea affects an estimated 1 billion people worldwide — 80% undiagnosed. The condition causes repeated breathing pauses during sleep, dropping blood oxygen and fragmenting sleep architecture. Untreated, it doubles the risk of heart attack and stroke.</p><h2>How a smartwatch screens for sleep apnea</h2><p>Lumivex continuously monitors SpO2 during sleep. If oxygen drops below 90% for more than 5 cumulative minutes in a night, the watch flags a potential apnea event. Combined with movement data (frequent waking is an apnea sign) and heart rate variability patterns, the AI assigns a risk score.</p><h2>What it CANNOT do</h2><p>Distinguish between obstructive sleep apnea (OSA), central sleep apnea (CSA), and mixed apnea. Determine the exact Apnea-Hypopnea Index (AHI) — this requires EEG, airflow sensors, and respiratory effort belts in a sleep lab. Replace a polysomnography (PSG) diagnosis for insurance or treatment purposes.</p><h2>When to see a doctor</h2><p>If your Lumivex repeatedly flags SpO2 drops or sleep disruption, schedule a sleep study. Take your Lumivex sleep data with you — it provides a useful screening baseline that can accelerate diagnosis. Early detection matters: CPAP treatment reduces cardiovascular risk by 64% in diagnosed patients.</p>` },
  { slug: 'firmware-4-2', title: 'Firmware 4.2: Readiness Score 2.0 and Sleep Staging',
    excerpt: 'The biggest update this year adds REM/deep sleep staging and a redesigned readiness algorithm.',
    category: 'Product Updates', author: 'James Whitfield', authorTitle: 'Co-CEO', readTime: '5 min', date: '2025-11-18', coverImage: '/generated/scene-office.webp',
    content: `<p>Firmware 4.2 is rolling out to all Lumivex devices starting today. This is our biggest algorithm update since HealthCore AI v3.0 launched.</p><h2>What is new</h2><p><strong>Sleep Staging</strong>: The watch now classifies each sleep epoch into Wake, REM, Light, and Deep sleep — with 92% accuracy compared to polysomnography. You can see exactly how much of each stage you got and compare to age-matched norms.</p><p><strong>Readiness Score 2.0</strong>: The daily 0-100 score now incorporates HRV trend (3-day rolling), sleep stage distribution (not just duration), and training load balance. A score above 85 means you are primed for high-intensity training. Below 50 suggests prioritizing recovery.</p><p><strong>Illness Risk Forecast</strong>: Using skin temperature baseline shifts, resting heart rate elevation, and HRV suppression, the watch now provides a 48-hour illness risk forecast. In beta testing, this feature provided early warning of 73% of reported cold and flu cases — an average of 36 hours before the user felt symptoms.</p><h2>How to update</h2><p>Open the Lumivex app → Settings → Firmware → Check for Updates. The update takes about 8 minutes. Ensure your watch has at least 30% battery and stays connected to Wi-Fi throughout. All health data is preserved.</p>` },
];

export function getPost(slug: string): Post | undefined { return posts.find(p => p.slug === slug); }
export function getPostSlugs(): string[] { return posts.map(p => p.slug); }
